services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: morgans-backend
    ports:
      - "8000:8000"
    volumes:
      - backend-data:/data
    networks:
      - shared-services

volumes:
  backend-data:

networks:
  shared-services:
    external: true